# Generated by Django 3.2.9 on 2021-12-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusercreation',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
