# Generated by Django 3.2.9 on 2021-11-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_userprofile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='media/files'),
        ),
    ]
