# Generated by Django 3.2.9 on 2021-11-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to='media/posts'),
        ),
    ]
