# Generated by Django 3.2.9 on 2021-11-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_messagemodel_threadmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
