# Generated by Django 3.2.9 on 2021-12-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_auto_20211201_0119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_user',
        ),
    ]
